### ISSUE TITLE
gnutar not installed by default on Mac OS X, and when it is, it's "gtar"

### ISSUE THREAD

**Issue by CharlesB2** [meitar/git-archive-all.sh#11]
Maybe a more friendly message could be helpful, or something in the docs, to tell Mac users to run `brew install gnu-tar`.

I don't know the history of line 107 (`[[ $(uname) == "Darwin" ]] && TARCMD=gnutar`) (maybe macports?), but when it is installed, it is linked as `gtar`

**Comment by meitar** [comment]
History for this line is in 9c3dbd639d642a699a5621c676616c6af99eab63. Apparently Mac OS X used to ship with `gnutar` installed by default but no longer does. This should probably be fixed to explicit test for support of the `--concatenate` option and complain if it's not available, rather than trying to do operating system detection and assuming the correct kind of `tar` is installed.
