### ISSUE TITLE
--format tar.gz is unintuitive or broken

### ISSUE THREAD

**Issue by BenWiederhake** [meitar/git-archive-all.sh#25]
With `--format tar` I get the expected results: A single archive that contains all source files, and the /tmp directory is left clean.

(On an unrelated note: `git-archive` supports the `--format=foo` syntax, but `git-archive-all.sh` only supports the `--format foo` [note the space] syntax. Why?)

With `--format tar.gz` in the first run, I get a single archive that contains *only* the top-level source files, and /tmp is cluttered with `middle.tar.gz` and `middle.inner.tar.gz`.

With `--format tar.gz` in the second run, I get an error message, saying that it can't overwrite `/tmp/middle.tar.gz`, and a new file `/tmp/outer.tar.gz` shows up.

With `--format tar.gz` in the third+ run, I get an error message, saying that it can't overwrite `/tmp/outer.tar.gz`.

It looks like the section `Concatenate archives into a super-archive` doesn't properly handle the case of `.tar.gz`

**Comment by meitar** [comment]
> On an unrelated note: git-archive supports the --format=foo syntax, but git-archive-all.sh only supports the --format foo [note the space] syntax. Why?

Simply because bash argument parsing is a pain and I never took the time to support both the space-separated and equal-separated syntax. *shrug* Could be a useful enhancement, I guess.

> It looks like the section Concatenate archives into a super-archive doesn't properly handle the case of .tar.gz

Right. Currently, `git-archive-all` doesn't support `.tar.gz` format because you can simply do `./git-archive-all.sh outfile && gzip outfile` instead. This may be changed, see #18.
